

## Configuracion de Spring
spring:
  application:
    name: ms-cajaahorro-administracion
  datasource:
    url: jdbc:postgresql://localhost:5432/gmcajaahorro
    username: postgres
    password: Administrador


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ## ddl-auto: create-drop
    defer-datasource-initialization: true



## Configuracion de Instancia
server:
  port: 8092

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-cajaahorro-administracion

    ## Configuracion secundaria (custom)
getSecuencia:
   url: http://ms-cajaahorro-utilitario/secuencia





